### ISSUE TITLE
err reading config file

### ISSUE THREAD

**Issue by juippis** [arzano/pgo#1]
Hey, 

anytime I use *pgo* it prints me the following two lines:
```
err reading config file
open /home/joonas/.pgo: no such file or directory
```
There's no example config file either to be found that I could use as a sample? Maybe either provide an example config, or print this once the package is emerged, and not everytime the program is run? :)

https://gitweb.gentoo.org/repo/gentoo.git/tree/media-video/yle-dl/yle-dl-20200807.ebuild#n51

**Comment by arzano** [comment]
Hi, 

Thank you for the suggestion. The error message should already have been resolved in the latest version (should be visible in the live version). Apart from this, some further documentation on the config file is definitely one of the next things I am going to tackle here.

**Comment by juippis** [comment]
Yep, it seems fixed on -9999. Waiting for a next release!
